spring.application.name=Api learning
spring.data.mongodb.uri=mongodb+srv://nanigopalr972:Wlp3u8vaJti2hd9x@cluster0.0sejouj.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.database=blogdb
